# Generated by Django 4.2.11 on 2026-03-28 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('donation_type', models.CharField(choices=[('monetary', 'Monetary'), ('in_kind', 'In-Kind'), ('service', 'Service')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Description of donation')),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_beneficiaries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('families_impacted', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('children_benefited', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('key_achievements', models.TextField(help_text='Key achievements and outcomes')),
                ('challenges_faced', models.TextField(blank=True, help_text='Challenges faced during project')),
                ('lessons_learned', models.TextField(blank=True)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Project completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('report_document', models.FileField(blank=True, null=True, upload_to='impact_reports/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='JSON list of image URLs')),
            ],
            options={
                'verbose_name': 'Impact Report',
                'verbose_name_plural': 'Impact Reports',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('director', 'Director'), ('coordinator', 'Coordinator'), ('volunteer', 'Volunteer'), ('donor', 'Donor')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('mission', models.TextField(help_text="Organization's mission statement")),
                ('vision', models.TextField(help_text="Organization's vision statement")),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('established_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('objective', models.TextField(help_text='Project objectives and goals')),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('community', 'Community Development'), ('women', 'Women Empowerment'), ('disaster', 'Disaster Relief'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_beneficiaries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('lead_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='ngo_app.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ngo_app.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='ngo_app_org_slug_5b7a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='ngo_app_org_status_62ad0a_idx'),
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ngo_app.organization'),
        ),
        migrations.AddField(
            model_name='impact',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='ngo_app.project'),
        ),
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='ngo_app.organization'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='ngo_app.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='ngo_app_pro_organiz_9288b7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='ngo_app_pro_categor_711cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='ngo_app_pro_slug_1dcca8_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['organization', 'status'], name='ngo_app_mem_organiz_0d533f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['role'], name='ngo_app_mem_role_479cb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('organization', 'email')},
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['organization', 'status'], name='ngo_app_don_organiz_c3f0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='ngo_app_don_donatio_b7a976_idx'),
        ),
    ]
